spring:
  application:
    name: aop
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always # schema.sql, data.sql ?? ??
      schema-locations: schema.sql
      data-locations: data.sql
  h2:
    console:
      enabled: true

